server:
  port:
    8081

spring:
  application:
    name: login
  datasource:
    url: jdbc:mysql://localhost:3306/dashcrypto_login
    username: root
    password: master
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000